spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/blog?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC}
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: validate
  liquibase:
    enabled: true



