insert into posts (is_active, moderation_status, moderator_id, user_id, time, title, text, view_count) values (true , 'ACCEPTED', 1,1,'2022-01-01 19:22:17', 'индивидуальный проект', 'представляю вашему вниманию индивидуальный проект по JAVA - блоговый движок', 5);
insert into posts (is_active, moderation_status, moderator_id, user_id, time, title, text, view_count) values (true , 'NEW', null ,2,'2022-01-01 19:22:18', 'dolorem', 'Aut inventore cumque sed quam possimus quia sunt. Officia velit odio tenetur perferendis et. Ut voluptatum maiores adipisci.', 5);
insert into posts (is_active, moderation_status, moderator_id, user_id, time, title, text, view_count) values (true , 'NEW', null,3,'2022-01-01 19:22:19', 'ad', 'Nihil harum aut harum odit nemo et enim et. Molestiae nam ipsum esse quo quisquam soluta. Iure debitis repellat magni quam.' , 5);
insert into posts (is_active, moderation_status, moderator_id, user_id, time, title, text, view_count) values (true , 'NEW', null,4,'2022-01-01 19:22:20', 'reiciendis', 'Qui voluptas laudantium maiores. Aut ut molestiae voluptatibus blanditiis ipsa. Iure eum tempore distinctio ad hic ipsa impedit. Dolor quos quas animi cupiditate.' , 5);
insert into posts (is_active, moderation_status, moderator_id, user_id, time, title, text, view_count) values (true , 'NEW', null,5,'2022-01-01 19:22:21', 'commodi', 'Eaque accusamus omnis explicabo atque odit natus. Voluptas cupiditate veritatis unde possimus exercitationem. Nihil velit vel nobis ut.', 5);
insert into posts (is_active, moderation_status, moderator_id, user_id, time, title, text, view_count) values (true , 'NEW', null,2,'2022-01-01 19:22:22', 'odit', 'Nulla odio eum ut enim in ad voluptas qui. Quia eum quis aut omnis dolor. Est accusantium non qui dolorum cum ut dolorem.', 5);
insert into posts (is_active, moderation_status, moderator_id, user_id, time, title, text, view_count) values (true , 'NEW', null,3,'2022-01-01 19:22:23', 'magnam', 'Qui sunt numquam excepturi. Dolores dolores est expedita quisquam qui eaque. Perferendis temporibus quo nihil quisquam et laboriosam.', 5);
insert into posts (is_active, moderation_status, moderator_id, user_id, time, title, text, view_count) values (true , 'NEW', null,4,'2022-01-01 19:22:24', 'aliquam', 'Sed sit error hic. Harum et aut dicta pariatur non. Placeat sequi quidem distinctio nihil est nisi iusto.', 5);
insert into posts (is_active, moderation_status, moderator_id, user_id, time, title, text, view_count) values (true , 'NEW', null,5,'2022-01-01 19:22:25', 'veritatis', 'Et aut et repudiandae harum ullam atque. Ducimus dignissimos saepe perferendis neque.', 5);

